# Generated by Django 3.2.23 on 2024-09-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockVisualiser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForexData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.TextField(null=True)),
                ('data', models.TextField(null=True)),
            ],
        ),
    ]
