# Generated by Django 3.2.23 on 2024-10-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockVisualiser', '0002_forexdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forexdata',
            name='data',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='data',
        ),
        migrations.AddField(
            model_name='forexdata',
            name='ata',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='ata',
            field=models.TextField(null=True),
        ),
    ]
