# Generated by Django 3.2.23 on 2024-10-07 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockVisualiser', '0003_auto_20241007_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forexdata',
            old_name='ata',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='ata',
            new_name='data',
        ),
    ]
